### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by jus51565** [mmxgn/minie#3]
Hi, thank you for sharing your code!
I implemented Miniepy as it was recommended in the README, but when I run "python3 demo.py" I get the following error message:

```
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I tried different methods that were suggested on the internet to resolve the issue, but the error message is still there. It does make the extractions tho. 
Are the extractions affected by this? Is there a way to resolve this? 
Thank you very much in advance!

**Comment by mmxgn** [comment]
Since it does not seem to be affecting extraction, I suggest you ignore it for now.

**Comment by jus51565** [comment]
Thank you for your answer! I still found an issue with the quantity extraction. For example: 
Input sentence: They own 30 cats.

> Extractions:
> 	Triple: "They"	"own"	"QUANT_O_1 cats"	
> 	Factuality: (+,CT)
> 	Attribution: NONE

It doesn't show the quantity somewhere as it is described in the paper. When I use other sentences with other quantities it is the same thing. Could this be related to the error I'm getting?

**Comment by Qiming-Liu** [comment]
> Hi, thank you for sharing your code! I implemented Miniepy as it was recommended in the README, but when I run "python3 demo.py" I get the following error message:
> 
> ```
> > SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> > SLF4J: Defaulting to no-operation (NOP) logger implementation
> > SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> ```
> 
> I tried different methods that were suggested on the internet to resolve the issue, but the error message is still there. It does make the extractions tho. Are the extractions affected by this? Is there a way to resolve this? Thank you very much in advance!

Download jar file here:
https://mvnrepository.com/artifact/org.slf4j/slf4j-api/1.7.32
and Put it in the target folder
