### ISSUE TITLE
Error while compiling MinIE

### ISSUE THREAD

**Issue by talha1503** [mmxgn/minie#6]
As written in the readme, I was compiling MinIE using `maven 3.8.5` . However, I was getting the following error: 

`[ERROR] Failed to execute goal on project minie: Could not resolve dependencies for project de.uni_mannheim:minie:jar:0.0.1-SNAPSHOT: Could not transfer artifact edu.stanford.nlp:stanford-corenlp:jar:models:3.8.0 from/to central (https://repo.maven.apache.org/maven2): GET request of: edu/stanford/nlp/stanford-corenlp/3.8.0/stanford-corenlp-3.8.0-models.jar from central failed: Premature end of Content-Length delimited message body (expected: 362,452,284; received: 18,865,505) -> [Help 1]  `

Could you please help me resolve this issue?

**Comment by mmxgn** [comment]
Hi,

Unfortunately I can't reproduce this since maven runs fine here. Can you try again? Maybe it was a blip. If it persists try cleaning maven cache and retrying.

**Comment by mmxgn** [comment]
Hi, 

Was the issue resolved?

**Comment by talha1503** [comment]
Yes. The issue got resolved :) I compiled it again, and it worked :)
